version: 2.1

jobs:
  test:
    macos:
      xcode: 13.4.0
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: xcodebuild test -scheme FileSystemEventPublisher -destination 'platform=macOS,arch=x86_64'

  build:
    macos:
      xcode: 13.4.0
    steps:
      - checkout
      - run:
          name: Build Application
          command: xcodebuild -scheme FileSystemEventPublisher -destination 'platform=macOS,arch=x86_64'

workflows:
  test_build:
    jobs:
      - test
      - build:
          requires:
            - test

